FROM openjdk:11 

MAINTAINER Carson Gross <carson.gross@montana.edu>

COPY . /usr/src/stringweb
WORKDIR /usr/src/stringweb

CMD ["java", "-cp", "target/StringWeb-jar-with-dependencies.jar", "edu.montana.csci.csci366.strweb.StringWeb"]
